---
- name: Configure iproute2
  template:
    src: rt_tables
    dest: "/etc/iproute2/rt_tables"

- name: Configure interfaces
  template:
    src: network-interfaces
    dest: "/etc/network/interfaces"
  notify: ifupdown eth1
