wcth_onion_service_v2_hostname: 'o7mcp5y4ibyjkcgs.onion'
wcth_onion_service_v2_private_key: '{{ vault_wcth_onion_service_v2_private_key }}'
wcth_onion_service:
  service_dir: '/var/lib/tor/onion_web_connectivity_v2'
  hs_version: 2
  hostname: "{{ wcth_onion_service_v2_hostname }}"
  private_key: "{{ wcth_onion_service_v2_private_key }}"
  ports:
  - service_port: 80
    local_ipv4: '127.0.0.1'
    local_port: 9020
