---
slackin_domains: slack.openobservatory.org -> http://slackin:3000'
slack_org: '{{ vault_slack_org }}'
slack_token: '{{ vault_slack_token }}'
slack_irc_dir: "/etc/slack-irc"
slack_irc_config: |
  [
    {
      "nickname": "slacktopus",
      "autoSendCommands": [
        ["PRIVMSG", "NickServ", "GHOST slacktopus {{ vault_slacktopus_password }}" ],
        ["NICK", "slacktopus"],
        ["PRIVMSG", "NickServ", "IDENTIFY {{ vault_slacktopus_password }}"]
      ],
      "server": "irc.oftc.net",
      "token": "{{ vault_slack_irc_token }}",
      "channelMapping": {
        {% for channel in vault_secret_channels %}
        "{{ channel.slack }}": "{{ channel.irc }}",
        {% endfor %}
        "#ooni": "#ooni",
        "#ooni-entropy": "#ooni-entropy"
      }
    }
  ]
