---
# for https://slack.openobservatory.org/
slackin_domains: slack.openobservatory.org -> http://slackin:3000
slack_org: '{{ vault_slack_org }}'
slack_token: '{{ vault_slack_token }}'
# for slack-irc gateway
slack_irc_dir: "/etc/slack-irc"
slack_irc_config: |
  [
    {
      "nickname": "slacktopus",
      "ircOptions": {
        "realName": "OONI Slack relay",
        "stripColors": true,
        "retryCount": 60,
        "retryDelay": 5000,
        "port": 6697,
        "secure": true,
        "autoSendCommands": [
          ["PRIVMSG", "NickServ", "GHOST slacktopus {{ vault_slacktopus_password }}" ],
          ["NICK", "slacktopus"],
          ["PRIVMSG", "NickServ", "IDENTIFY {{ vault_slacktopus_password }}"]
        ],
      },
      "server": "irc.oftc.net",
      "token": "{{ vault_slack_irc_token }}",
      "channelMapping": {
        {% for channel in vault_secret_channels %}
        "{{ channel.slack }}": "{{ channel.irc }}",
        {% endfor %}
        "#ooni": "#ooni",
        "#ooni-bots": "#ooni-bots",
        "#ooni-entropy": "#ooni-entropy"
      }
    }
  ]
