letsencrypt_admin_email: admin@openobservatory.org
letsencrypt_workdir: /var/lib/letsencrypt
letsencrypt_port: 80
letsencrypt_webroot: /var/www/letsencrypt
letsencrypt_confdir: /etc/letsencrypt
nginx_post_hook: '/usr/sbin/service nginx reload'
# Currently no pre_hook can be set to restart backend docker containers
# XXX this should be fixed when ooni-backend re-read TLS certificates
letsencrypt_pre_hook: "{%- if docker_deployment is defined -%}
    docker stop {{ docker_img_name }} {%- endif -%}"
letsencrypt_post_hook: "cp {{ letsencrypt_live_dir | default ('') }}/privkey.pem
    {{ letsencrypt_live_dir | default ('') }}/fullchain.pem
    {% if docker_deployment is defined %}
    {{ bind_oonibackend_tls_dir | default ('') }}
    {% else %}
    {{ oonibackend_tls_dir | default ('') }}
    {% endif %}
    {% if docker_deployment is defined %}
    && docker start {{ docker_img_name | default ('') }}
    {%- endif -%}"
letsencrypt_certbot_cmd: >
    certonly
    {% if letsencrypt_nginx is defined -%}
    --webroot -w {{ letsencrypt_webroot }}
    {%- else -%}
    --standalone
    {% endif %}
    {% if letsencrypt_test_cert is defined -%} --test-cert {% endif -%}
    --preferred-challenges http-01 --noninteractive --text --agree-tos
    --email {{ letsencrypt_admin_email }} --domains {{ letsencrypt_domains }}
    {% if docker_deployment is defined -%}
    --pre-hook "{{ letsencrypt_pre_hook }}" --post-hook "{{ letsencrypt_post_hook }}"
    {%- endif -%}
    {% if letsencrypt_nginx is defined -%}
    --post-hook "{{ nginx_post_hook }}"
    {%- endif -%}
letsencrypt_renew_cmd: >
    certbot
    {% if letsencrypt_force_renew is defined -%} --force-renew {% endif -%}
    {{ letsencrypt_certbot_cmd }}
