---
- name: install LVM
  when: ansible_hostname == 'ams-pg-test.ooni.org'
  apt:
    cache_valid_time: 86400
    name: lvm2

- name: Create vg.metadb Volume Group
  when: ansible_hostname == 'ams-pg-test.ooni.org'
  lvg:
    vg: vg.metadb
    pvs:
      - /dev/sda

- name: Create metadb logical volume
  when: ansible_hostname == 'ams-pg-test.ooni.org'
  lvol:
    vg: vg.metadb
    lv: metadb
    size: 100%VG

- name: Create ext4 filesystem for metadb
  when: ansible_hostname == 'ams-pg.ooni.org'
  filesystem:
    fstype: ext4
    dev: /dev/vg.metadb/metadb
    opts: -L metadb

- name: Mount ext4 metadb FS
  when: ansible_hostname == 'ams-pg.ooni.org'
  mount:
    fstype: ext4
    opts: noatime
    path: /var/lib/postgresql
    src: LABEL=metadb
    state: mounted

- name: Create btrfs filesystem for metadb
  when: ansible_hostname == 'ams-pg-test.ooni.org'
  filesystem:
    fstype: btrfs
    dev: /dev/vg.metadb/metadb
    opts: -L metadb

# TODO FIXME install kernel 5.8.0-0.bpo.2-cloud-amd64 on ams-pg-test to use 
# Reboot
# Ensure the running kernel is correct
- name: Mount btrfs metadb FS
  when: ansible_hostname == 'ams-pg-test.ooni.org'
  mount:
    fstype: btrfs
    opts: defaults,space_cache,noatime,compress=zstd:1,nodatacow,autodefrag
    path: /var/lib/postgresql
    src: LABEL=metadb
    state: mounted

- name: install PG11
  apt:
    cache_valid_time: 86400
    name:
      - postgresql-11

- name: Overwrite pg_hba.conf
  template:
    src: templates/pg_hba.conf
    dest: /etc/postgresql/11/main/pg_hba.conf
    mode: 0644
    owner: root

- name: Overwrite postgresql.conf
  template:
    src: templates/postgresql.conf
    dest: /etc/postgresql/11/main/postgresql.conf
    mode: 0644
    owner: root

- name: Enable and start service
  shell: systemctl enable --now postgresql.service

- name: Reload pg after conf change
  shell: systemctl reload postgresql.service

- name: allow incoming TCP connections to database
  blockinfile:
    path: /etc/ooni/nftables/tcp/5432.nft
    create: yes
    block: |
      add rule inet filter input ip saddr {{ lookup('dig', 'ams-jupyter.ooni.nu/A') }}         tcp dport 5432 counter accept comment "incoming psql"

- name: reload nftables service
  shell: systemctl reload nftables.service

- name: configure Netdata Postgres monitoring
  tags: netdata
  blockinfile:
    path: /etc/netdata/python.d/postgres.conf
    create: yes
    block: |
      socket:
        name     : 'local'
        user     : 'shovel'
        database : 'metadb'

- name: restart netdata service
  tags: netdata
  systemd:
    name: netdata.service
    state: restarted

