---
- name: Generate Letsencrypt certificates
  docker:
    name: "{{ letsencrypt_docker_name }}"
    image: "{{ letsencrypt_docker_image }}"
    ports:
    - "{{ letsencrypt_ports }}"
    volumes:
    - "{{ letsencrypt_workdir }}"
    - "{{ letsencrypt_confdir }}"
    command: "{{ letencrypt_certbot_cmd }}"
