---
- name: Creates {{ item }}
  file: >
    state=directory
    path={{ item }}
  with_items:
    - "{{ letsencrypt_workdir }}"
    - "{{ letsencrypt_confdir }}"

- name: Creates backend TLS dir
  file: >
    state=directory
    path="{{ bind_oonibackend_tls_dir }}"
  when: docker_deployment is defined

- name: Generate Letsencrypt certificates with docker
  docker:
    name: "{{ letsencrypt_docker_name }}"
    image: "{{ letsencrypt_docker_image }}"
    expose: "{{ letsencrypt_port }}"
    ports:
    - "{{ docker_ip }}:{{ letsencrypt_port }}:{{ letsencrypt_port }}"
    volumes:
    - "{{ letsencrypt_workdir }}:{{ letsencrypt_workdir }}"
    - "{{ letsencrypt_confdir }}:{{ letsencrypt_confdir }}"
    command: "{{ letsencrypt_certbot_cmd }}"
    state: reloaded

- name: Copy TLS specific backend files
  copy: >
    src="{{ item }}"
    dest="{{ bind_oonibackend_tls_dir }}"
  with_items:
    - "{{ letsencrypt_live_dir }}/privkey.pem"
    - "{{ letsencrypt_live_dir }}/fullchain.pem"
  when: docker_deployment is defined
