---
- name: Install Letsencrypt certbot
  apt:
    name:
    - certbot
    - python-certbot-nginx
    state: latest
    update_cache: yes
    cache_valid_time: '{{ apt_cache_valid_time }}'

- name: Find stale letsencrypt_renew_certs cron jobs
  find:
    paths: /etc/cron.d
    patterns: 'letsencrypt_renew_certs-*'
  register: find_results

- name: Remove stale letsencrypt_renew_certs cron jobs
  file:
    path: '{{ item.path }}'
    state: absent
  with_items: '{{ find_results.files }}'

- name: Remove state letsencrypt vhost
  file: path=/etc/nginx/sites-enabled/letsencrypt state=absent

- name: Ensure required directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "/etc/nginx/sites-enabled"
    - "/var/www/letsencrypt"

- name: Add letsencrypt vhost
  template:
    src: templates/letsencrypt-http
    dest: /etc/nginx/sites-enabled/letsencrypt-http

- name: Reload nginx to activate letsencrypt site
  service: name=nginx state=restarted

# NB: --standalone is not supported
- name: Generate Letsencrypt certificate with certbot package
  command: >
    certbot certonly
    --webroot -w /var/www/letsencrypt --preferred-challenges http
    --noninteractive --text --agree-tos
    --email {{ letsencrypt_admin_email }}
    --domains {{ letsencrypt_domains | join(',') }}
    --post-hook '/usr/sbin/service nginx reload'
  args: { creates: '/etc/letsencrypt/renewal/{{ letsencrypt_domains | first }}.conf' }
...
