
- name: create group
  group: name={{ item.login }} gid={{ item.id }} state=present
  with_items: '{{ passwd.values() }}'
  loop_control:
    label: '{{ item.login }}'

- name: create user
  user:
    name: '{{ item.login }}'
    group: '{{ item.login }}'
    uid: '{{ item.id }}'
    comment: '{{ item.comment }}'
    shell: '{{ (item.id >= 10000) | ternary("/bin/bash", "/usr/sbin/nologin") }}'
    createhome: '{{ item.id >= 10000 }}'
    home: '{{ (item.id >= 10000) | ternary("/home/" ~ item.login, "/nonexistent") }}'
    state: present
  with_items: "{{ passwd.values() }}"
  loop_control:
    label: "{{ item.login }}"

