---
- name: Clone {{ ooni_explorer_git }} repository
  git:
    repo: "{{ ooni_explorer_git }}"
    dest: "{{ ooni_explorer_path }}"
  become_user: "{{ ooni_explorer_user }}"

- name: Install bower package
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - bower
    - grunt

- name: Install bower package requirements
  bower:
    path: "{{ ooni_explorer_path }}"
  become_user: "{{ ooni_explorer_user }}"

- name: Install node package requirements
  npm:
    path: "{{ ooni_explorer_path }}"
    state: latest
  become_user: "{{ ooni_explorer_user }}"

- name: Grunt build
  command: grunt build
  args:
    chdir: "{{ ooni_explorer_path }}"
  become_user: "{{ ooni_explorer_user }}"
...
