---
## - include: apt.yml # temporary disabled

- name: Create {{ ooni_explorer_user }} user
  user:
    name: "{{ ooni_explorer_user }}"

- name: Remove default nginx virtual host config
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Add ooni-explorer nginx virtual host config
  template:
    src: nginx-ooni-explorer.conf.j2
    dest: /etc/nginx/sites-enabled/ooni-explorer
    owner: root
    group: root
    mode: 0444
  notify: reload nginx

## - include: build.yml # temporary disabled

- name: Template {{ ooni_explorer_datasources }}
  template:
    src: datasources.production.js.j2
    dest: "{{ ooni_explorer_datasources }}"
    owner: root
    group: "{{ ooni_explorer_user }}"
    mode: 0440

- name: Install node-ooni-explorer.service
  template:
    src: node-ooni-explorer.service.j2
    dest: "{{ ooni_explorer_unit_path }}"

- name: Start node-ooni-explorer.service
  systemd:
    name: node-ooni-explorer.service
    state: started
    enabled: yes
    daemon_reload: yes
...
