---
- name: install PostgreSQL 13
  tags: postgresql13
  apt:
    cache_valid_time: 86400
    name:
      - postgresql-13

- name: Overwrite pg_hba.conf
  tags: postgresql13
  template:
    src: templates/pg_hba.conf
    dest: /etc/postgresql/13/main/pg_hba.conf
    mode: 0644
    owner: root

- name: Prepare postgresql.conf
  tags: postgresql13
  template:
    src: templates/postgresql.conf
    dest: /etc/postgresql/13/main/postgresql.conf
    mode: 0644
    owner: root

- name: Enable and start service
  tags: postgresql13
  shell: systemctl enable --now postgresql.service

- name: Reload pg after conf change
  tags: postgresql13
  shell: systemctl reload postgresql.service

- name: allow incoming TCP connections to database
  tags: pg-nftables
  blockinfile:
    path: /etc/ooni/nftables/tcp/5432.nft
    create: yes
    block: |
      add rule inet filter input ip saddr {{ lookup('dig', 'jupyter.ooni.org/A') }} tcp dport 5432 counter accept comment "psql from jupyter.ooni.org"

- name: reload nftables service
  tags: pg-nftables
  shell: systemctl reload nftables.service

- name: Create metadb
  tags: postgresql13
  become_user: postgres
  postgresql_db:
    name: metadb

- name: Create readonly user
  tags: postgresql13
  become_user: postgres
  postgresql_user:
    db: metadb
    name: readonly
    # already made public
    password: b2HUU6gKM19SvXzXJCzpUV
    role_attr_flags: NOSUPERUSER
    priv: ALL
    ssl_mode: require

- name: Create shovel user
  tags: postgresql13
  become_user: postgres
  postgresql_user:
    db: metadb
    name: shovel
    # already made public
    password: yEqgNr2eXvgG255iEBxVeP
    role_attr_flags: NOSUPERUSER
    priv: ALL
    ssl_mode: require

- name: Create amsapi user
  tags: postgresql13
  become_user: postgres
  postgresql_user:
    db: metadb
    name: amsapi
    role_attr_flags: NOSUPERUSER
    priv: ALL
    ssl_mode: require

- name: Simple select query
  tags: postgresql13
  postgresql_query:
    db: metadb
    query: SELECT version()
    login_user: readonly

- name: configure Netdata Postgres monitoring
  tags: netdata
  blockinfile:
    path: /etc/netdata/python.d/postgres.conf
    create: yes
    block: |
      socket:
        name     : 'local'
        user     : 'shovel'
        database : 'metadb'
#  CREATE SUBSCRIPTION metadbsub CONNECTION 'dbname=metadb host=ams-pg-test.ooni.org user=readonly' PUBLICATION metadbpub;

- name: restart netdata service
  tags: netdata
  systemd:
    name: netdata.service
    state: restarted

