---
- name: Ensure openssl is installed
  apt:
    name: "openssl"
    state: present

- name: Create node_exporter private dir
  file:
    path: "{{ node_exporter_private_path}}"
    state: directory
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: 0700

- name: Generate host private key
  command: openssl genrsa -out {{ node_exporter_ssl_key_path }} 4096 creates={{ node_exporter_ssl_key_path }}

- name: Set private key permissions
  file:
    path: "{{ node_exporter_ssl_key_path }}"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: "0700"

- name: Generate CSR request
  command: openssl req -new -sha256 -subj "{{ node_exporter_ssl_cert_subj }}" -key {{ node_exporter_ssl_key_path }} -out {{ node_exporter_ssl_csr_path }} creates={{ node_exporter_ssl_csr_path }}

- name: Set CSR permissions
  file:
    path: "{{ node_exporter_ssl_csr_path }}"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: "0700"

- name: Create local private dir
  file:
    path: "{{ local_private_path }}"
    state: directory
    mode: 0700
  delegate_to: localhost

- name: Fetch the CSR from the host
  fetch:
    src: "{{ node_exporter_ssl_csr_path }}"
    dest: "{{ local_private_path }}/{{ inventory_hostname }}.csr"
    flat: yes

# -- BEGIN RUN ON THE CONTROLLER HOST --

- name: Write the root ca private key to the private dir
  copy:
    content: "{{ prometheus_root_ca_key }}"
    dest: "{{ local_private_path }}/prometheus_root_ca.key"
  delegate_to: localhost

- name: Set root ca key permissions
  file:
    path: "{{ local_private_path }}/prometheus_root_ca.key"
    mode: "0700"
  delegate_to: localhost

- name: write the root ca cert to temporary directory
  copy:
    content: "{{ prometheus_root_ca_pem }}"
    dest: "{{ local_private_path }}/prometheus_root_ca.pem"
  delegate_to: localhost

- name: Set root ca cert permissions
  file:
    path: "{{ local_private_path }}/prometheus_root_ca.pem"
    mode: "0700"
  delegate_to: localhost

- name: Generate signed SSL certificate
  command: openssl x509 -req -sha256 -days 1024 -in "{{ local_private_path }}/{{inventory_hostname}}.csr" -CA "{{ local_private_path }}/prometheus_root_ca.pem" -CAkey "{{ local_private_path }}/prometheus_root_ca.key" -CAcreateserial -out "{{ local_private_path }}/{{ inventory_hostname }}.cert" -extensions v3_ca creates="{{ local_private_path }}/{{ inventory_hostname }}.cert"
  delegate_to: localhost

# -- END RUN ON THE CONTROLLER HOST --

- name: Copy to remote machine the signed certificate
  copy:
    src: "{{ local_private_path }}/{{ inventory_hostname }}.cert"
    dest: "{{ node_exporter_ssl_cert_path }}"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: "0700"
