---
groups:
- name: OONI Alerts
  rules:
  - alert: NASBackupSilent
    expr: time() - push_time_seconds{exported_instance="hellais-nas"} > 16 * 3600
    annotations:
      summary: 'hellais-nas is silent for {{ $value | humanizeDuration }}'

  - alert: NASRsyncFailure
    expr: rsync_returncode{exported_instance="hellais-nas"} != 0
    for: 16h # rsync is launched at 08:00 and 22:00, that's 14h and 10h gap
    annotations:
      summary: '`rsync` exitcode: {{ $value }}'
...
