---
- name: Install ooni-backend via pip
  pip: name="{{oonibackend_package}}" state="latest"
- name: Create ooni log directory
  file: path=/var/log/ooni state=directory
- name: Create ooni backend archive directory
  file: path=/var/spool/ooni/backend/archive state=directory
- name: Create ooni backend raw reports directory
  file: path=/var/spool/ooni/backend/raw_reports state=directory
- name: Create ooni backend tor directory
  file: path=/var/spool/ooni/backend/tor state=directory
