---
- name: Wait for hidden services to bootstrap
  wait_for: >
    path="{{ bind_oonibackend_conf }}"
    search_regex="Started hidden service"
    delay="30"

- name: List available HS dirs
  command: ls "{{ bind_tor_datadir }}"
  register: hsdirs_list

- name: Assign hidden services hostnames to variables
  shell: cat "{{ bind_tor_datadir }}/{{ item }}/hostname"
  register: hs_hostname
  with_items: "{{ hsdirs_list.stdout_lines }}"

- name: Template "{{ bouncer_file }}"
  template: >
    src="bouncer_base.yaml.j2"
    dest="{{ bind_bouncer_base_file }}"
    backup="yes"
