---
- name: Add required Debian apt repository for obfs4proxy >= version 0.5
  apt_repository: >
    repo='{{ custom_debian_repository }}'
    state=present
    update_cache=yes

- name: Configure APT preferences for Debian
  template: >
    src=debian.pref.j2
    dest=/etc/apt/preferences.d/debian-{{ custom_debian_release_name }}.pref
    owner=root
    group=root
    mode=0644
    backup=yes

- name: Install obfs4proxy
  apt: >
    update_cache=yes
    default_release={{ custom_debian_release_name }}
    name=obfs4proxy
