- name: install requirements for compiling python extensions
  apt: 
    pkg: "{{ item }}"
    state: latest
  with_items: ["build-essential", "python-dev", "python-setuptools", "openssl",
               "libsqlite3-dev", "libffi-dev"]
