---
- name: Install certbot and Python library
  apt:
    name:
    - certbot
    - python3-prometheus-client
    state: latest
    update_cache: yes
    cache_valid_time: '{{ apt_cache_valid_time }}'
  when: ansible_distribution_release == 'buster'

- name: Ensure required directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "/etc/nginx/sites-enabled"
    - "/etc/nginx/sites-available"
    - "/var/www/letsencrypt/.well-known/acme-challenge/"
    - "/etc/ooni"

- name: Empty /etc/nginx/sites-available/default
  shell: echo > /etc/nginx/sites-available/default

- name: Add letsencrypt dedicated sites-enabled file
  template:
    src: templates/letsencrypt-http
    dest: /etc/nginx/sites-enabled/letsencrypt-http
    mode: 0644
    owner: root
  notify: reload nginx

# Run certbot to create a new cert if needed
# It's one certificate for all the domains in letsencrypt_domains
# named after the first domain
# If new domains have been added certbot updates the cert (--expand)
# otherwise it keeps the existing cert (--keep)
- name: Create Letsencrypt certificates for the first time
  args:
  command: >
    certbot certonly
    --webroot --webroot-path /var/www/letsencrypt
    --preferred-challenges http
    --noninteractive --text --agree-tos
    --email {{ letsencrypt_admin_email }}
    --domains {{ letsencrypt_domains | join(',') }}
    --expand
    --keep

- name: Ensure certbot timer runs
  systemd:
    name: certbot.timer
    state: started
    enabled: yes
...
