bouncer_ipv4: 127.0.0.1
bouncer_port: 9000

collector_ipv4: 127.0.0.1
collector_port: 9010

web_connectivity_ipv4: 127.0.0.1
web_connectivity_port: 9020

registry_ipv4: 127.0.0.1
registry_port: 9030

orchestrate_ipv4: 127.0.0.1
orchestrate_port: 9031
