# ooni-bouncer
bouncer_domain: 'mia-ps.ooni.io'
bouncer_data_dir: '/srv/bouncer'
bouncer_port: 9000
# ooni-collector
collector_domain: 'mia-ps.ooni.nu'
collector_data_dir: '/srv/collector'
collector_port: 9010
# probe-services role
probe_services_domain: "mia-ps.ooni.nu"
bouncer_port: 9000
collector_port: 9010
registry_port: 9030
orchestrate_port: 9031
blackhole_ip: "37.218.241.80"
blackhole_gateway: "37.218.241.254"
anycast_ip: "37.218.244.15"
anycast_gateway: "37.218.244.254"

with_nginx: no
