local_pem_path: private
cert_munin: ssl-cert-munin.pem
key_munin: ssl-key-munin.pem
local_ssl_cert_munin: "{{ local_pem_path }}/{{ cert_munin }}"
local_ssl_key_munin: "{{ local_pem_path }}/{{ key_munin }}"
key_path_munin: /etc/ssl/private
cert_path_munin: /etc/ssl/certs
munin_conf_file: munin.conf
munin_conf: /etc/munin
remote_ssl_cert_munin: "{{ munin_conf }}/{{ cert_munin }}"
remote_ssl_key_munin: "{{ munin_conf }}/{{ key_munin }}"
munin_alerts:
  - {
    name: "contact-notify",
    email: "contact+notifications@openobservatory.org",
    subject: "Munin notification for ${var:group} :: ${var:host}",
    level: "critical"
  }
