---
# - name: Install apt dependencies
#   apt:
#     pkg: {{ item }}
#     state: latest
#   with_items: 
#     - wget
#     - unzip
#     - traceroute
#     - python-pip
#     - libfontconfig1
#     - python-termcolor
#     - python-requests
- name: Update all packages
  yum: name=* state=latest
  sudo: yes
- name: Update all packages
  yum: name={{ item }} state=latest
  sudo: yes
  with_items:
    - git
    - tar
    - bzip2
    - unzip
    - wget
    - traceroute
    - python-pip
    - fontconfig
    - psmisc
- name: fetch phantomjs
  get_url:
    url: "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2" # XXX parametrise arch
    dest: /tmp/
  register: phantomjs_archive

- name: Unarchive phantomjs_archive
  unarchive:
    src: "/tmp/phantomjs-1.9.8-linux-x86_64.tar.bz2"
    dest: "/tmp/"
    copy: no

- name: Install phantomjs
  command: "cp /tmp/phantomjs-1.9.8-linux-x86_64/bin/phantomjs /usr/local/bin"
  sudo: yes 

- name: Set permissions on phantomjs
  file: path=/usr/local/bin/phantomjs state=file mode=0755
  sudo: yes

- name: Install virtualenvwrapper
  pip: name="virtualenvwrapper" state=present
  sudo: yes

- name: Configure virtualenvwrapper
  lineinfile: 
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ item }}"
  with_items:
    - "export WORKON_HOME=$HOME/virtualenvs"
    - "source /usr/local/bin/virtualenvwrapper.sh"

- name: Create ~/virtualenvs/
  file: path="{{ ansible_env.HOME }}/virtualenvs" state=directory

- name: Clone the trackmap repository to the home
  git: repo=https://github.com/vecna/trackmap.git dest={{ ansible_env.HOME }}/trackmap

- name: Install trackmap requirements
  pip: requirements={{ ansible_env.HOME }}/trackmap/requirements.txt
        virtualenv={{ ansible_env.HOME }}/virtualenvs/{{ virtualenv_name }}
        virtualenv_site_packages=yes

