---
- name: Perform analysis
command: "{{ ansible_env.HOME }}/virtualenvs/{{ virtualenv_name }}/bin/python perform_analysis.py -l -c {{ country_code }}"
  args:
    chdir: "{{ ansible_env.HOME}}/trackmap/"
