go_arch: amd64

prometheus_user:   "{{ passwd.prometh.login }}"
prometheus_group:  "{{ passwd.prometh.login }}"

prometheus_base:         /srv/prometheus
prometheus_config_path:          /srv/prometheus/config
prometheus_db_path:              /srv/prometheus/data
prometheus_rule_path:            "{{ prometheus_config_path }}/rules"
prometheus_file_sd_config_path:  "{{ prometheus_config_path }}/targets"

prometheus_listen_address: ":9090"

prometheus_version: 1.6.0
prometheus_download_url: https://github.com/prometheus/prometheus/releases/download

prometheus_basename: "prometheus-{{ prometheus_version }}.linux-{{ go_arch }}"
prometheus_tarball_url: "{{ prometheus_download_url }}/v{{ prometheus_version }}/{{ prometheus_basename}}.tar.gz"
prometheus_sha256sums_url: "{{ prometheus_download_url }}/v{{ prometheus_version }}/sha256sums.txt"
prometheus_sha256sums: "{{ playbook_dir }}/cache/prometheus-{{ prometheus_version}}.SHA256SUMS"
prometheus_path: "{{ prometheus_base }}/{{ prometheus_basename }}"

prometheus_monitoring_cert: "{{ prometheus_base }}/prometheus.monitoring.pem"
prometheus_basic_auth_user: "prometheus"
prometheus_basic_auth_password: "{{ CHANGE_ME }}"

alertmanager_url: "http://127.0.0.1:9093"
