---
- name: Install apt package python-pip
  apt: >
    update_cache=yes
    name=python-pip

- name: Install pip package oonibackend
  pip: name=oonibackend version=1.3.7

- name: Install test helper systemd service file
  notify:
  - systemctl daemon-reload
  - restart web-connectivity-th
  template:
    src: web-connectivity-th.service
    dest: /etc/systemd/system/web-connectivity-th.service

- name: Write basic monitor script
  template:
    name: "{{ web_connectivity_user }}"
    group: "{{ web_connectivity_user }}"
    mode: "u+rwx"
    src: "if-nok-restart.sh"
    dest: "{{ web_connectivity_data_dir }}/if-nok-restart.sh"

- cron:
    name: "check every minute if the service is OK"
    minute: "*"
    hour: "*"
    user: "root"
    job: "{{ web_connectivity_data_dir }}/if-nok-restart.sh"
