---
- name: Install pip package docker-compose
  pip: name=oonibackend version=1.3.6

- name: Install test helper systemd service file
  notify:
  - systemctl daemon-reload
  - restart web-connectivity-th
  template:
    src: web-connectivity-th.service
    dest: /etc/systemd/system/web-connectivity-th.service
