
- name: Installs packages
  tags: monitoring, prometheus
  apt:
    install_recommends: no
    cache_valid_time: 86400
    name:
      - prometheus-alertmanager

- name: Configure Alertmanager templates
  tags: monitoring, prometheus
  notify:
  - reload alertmanager
  copy:
    src: "{{ item }}"
    dest: /etc/prometheus/alertmanager_templates/
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - templates/*.tmpl

- name: Configure Alertmanager
  tags: monitoring, prometheus
  notify:
  - reload alertmanager
  template:
    src: alertmanager.yml.j2
    dest: /etc/prometheus/alertmanager.yml"
    owner: root
    group: root
    mode: 0644
    validate: 'amtool check-config %s'
