---
collector_port: 8888

collector_user: 'collector'
sync_user: 'sync-user'
collector_tag: '20190221-0980b82a'
collector_data_dir: '{{ CHANGE_ME }}' # it varies across collectors
collector_domain: '{{ CHANGE_ME }}'
with_nginx: yes
...
