---
- name: install some common packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 28800
    install_recommends: false
  with_items:
    - ca-certificates
    - tmux
    - screen # art@ prefers :) old-school
    - vim
    - lsof
    - strace
    - tcpdump
    - curl
    - mtr
...
