---
- name: "Install dependencies"
  apt:
    name:
      - 'unzip'
      - 'vim'
    update_cache: yes
    state: latest

- name: create piwik group
  group: name={{ piwik_group }} state=present

- name: create piwik user
  user:
    name: '{{ piwik_user }}'
    group: '{{ piwik_group }}'
    comment: 'Piwik user'
    state: present

- name: Create folder
  file:
    path: "{{ app_path }}{{ item }}"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    state: directory
  with_items: "{{ deploy_create_folders }}"

- name: Configure
  template:
    src: config.ini.php.j2
    dest: "{{ app_path }}/shared/config/config.ini.php"

- import_tasks: setup-mysql.yml
- import_tasks: setup-php.yml
- import_tasks: setup-nginx.yml
- import_tasks: setup-piwik.yml
