---
- name: "Install PHP dependencies"
  apt:
    name:
      - 'php7'
      - 'php7-cli'
      - 'php7-fpm'
      - 'php7-common'
      - 'php7-curl'
      - 'php7-gd'
      - 'php7-xml'
      - 'php7-mbstring'
      - 'php7-mysql'
    update_cache: yes
    state: latest
