---
- name: restart node_exporter
  service:
    name: node_exporter
    state: restarted
- name: restart seeksample
  service:
    name: seeksample
    state: restarted
- name: restart tcpmetrics
  service:
    name: tcpmetrics
    state: restarted
...
