- name: Install config file
  template:
    src: blackbox.yml.j2
    dest: "/etc/prometheus/blackbox.yml"
    owner: root
    group: root
    mode: 0644
  notify:
  - restart blackbox_exporter
  tags: prometheus-conf
