---
- name: Install ooniprobe apt package dependencies
  apt: >
    update_cache=yes
    state=latest
    name={{ item }}
  with_items:
    - libgeoip-dev
    - libdumbnet-dev
- name: Pip install cffi and ooniprobe
  pip: >
    state=latest
    name={{ item }}
  with_items:
    - cffi
    - 'git+https://github.com/TheTorProject/ooni-probe.git#egg=ooniprobe'
