- name: create group
  group: name=afredis state=present

- name: create user
  user:
    name: "afredis"
    group: "afredis"
    comment: "afredis for Pipeline"
    state: present
  register: afredis_user

- name: redis .../etc directory
  file: dest=/srv/etc/af-redis state=directory owner=root group=root mode=0755
- name: redis .../etc/redis.conf
  template: dest=/srv/etc/af-redis/redis.conf src=af-redis.conf mode=0640 owner=root group=afredis
- name: redis /data directory
  file: dest=/srv/af-redis state=directory owner=afredis group=afredis mode=0750
- name: docker run redis
  docker_container:
    image: redis:3.2
    name: af-redis
    hostname: af-redis
    networks: [{name: af}]
    purge_networks: true # drop `bridge` network
    volumes:
      - /srv/etc/af-redis:/usr/local/etc:ro
      - /srv/af-redis:/data:rw
    command: /usr/local/etc/redis.conf
    user: "{{ afredis_user.uid }}:{{ afredis_user.group }}"
    restart_policy: unless-stopped
