- name: get the user id
  shell: >
    egrep "^{{ login }}:" /etc/passwd | awk -F: '{ print $4 }'
  changed_when: false
  register: user_id

- name: update shared airflow group
  lineinfile:
    dest: /srv/etc/af-share-{{ airflow_tag }}/group
    line: "{{ login }}:x:{{ user_id.stdout }}:"

- name: update shared airflow passwd
  lineinfile:
    dest: /srv/etc/af-share-{{ airflow_tag }}/passwd
    line: "{{ login }}:x:{{ user_id.stdout }}:{{ user_id.stdout  }}::/usr/local/airflow:/bin/bash"
