# ooni-bouncer
bouncer_domain: 'mia-ps2.ooni.io'
bouncer_data_dir: '/srv/bouncer'
bouncer_port: 9000
# ooni-collector
collector_domain: 'mia-ps2.ooni.nu'
collector_data_dir: '/srv/collector'
collector_port: 9010
# probe-services role
probe_services_domain: "mia-ps2.ooni.nu"
registry_port: 9030
orchestrate_port: 9031
with_nginx: no

collector_onion_hostname: "hcn5nqahdkds6cjv.onion"
collector_onion_private_key: "{{ vault_collector_onion_private_key }}"
collector_service_v2:
  service_dir: '/var/lib/tor/onion_collector_v2'
  hs_version: 2
  ports:
  - service_port: 80
    local_ipv4: '127.0.0.1'
    local_port: "80"
