---
- import_playbook: ansible-version.yml

- hosts: ams-explorer.ooni.nu
  roles:
    - role: docker
    - role: letsencrypt
      letsencrypt_domains:
        - 'ams-explorer.ooni.nu'
        - 'explorer.ooni.io'
        - 'explorer.ooni.torproject.org'
        - 'explorer.ooni.org'
        - 'explorer-beta.ooni.io'
        - 'ooni-explorer-next.test.ooni.io'
      tags: letsencrypt
    - role: explorer
      explorer_domain: 'ams-explorer.ooni.nu'
      tags: explorer

- hosts: mia-explorer-test.ooni.nu
  roles:
    - role: docker
      tags: test
    - role: letsencrypt
      letsencrypt_domains:
        - 'mia-explorer-test.ooni.nu'
        - 'explorer-test.ooni.io'
      tags: test
    - role: explorer
      explorer_next_tag: '20201007-d698422d'
      explorer_public_hostname: 'explorer-test.ooni.io'
      explorer_domain: 'mia-explorer-test.ooni.nu'
      tags: test
...
