---
- hosts: local:staging:testing
  vars:
    ansible_python_interpreter: "/usr/bin/python"
  roles:
    - common
    - docker_py

- hosts: local:staging:testing
  vars:
    ansible_python_interpreter: "/root/venv/bin/python2.7"
    enable_tls_bouncer: yes
    enable_tls_collector: yes
    enable_tls_web_connectivity: yes
    enable_bouncer: yes
    docker_deploymet: yes
  roles:
    - letsencrypt
    - ooni-backend
