---
- import_playbook: ansible-version.yml

- hosts: db-1.proteus.ooni.io
  vars:
    psql_db_name: "{{ orchestra_database_username }}"
    psql_db_user: "{{ orchestra_database_name }}"
    psql_db_passwd: "{{ orchestra_database_password }}"
  roles:
    - role: postgresql
      tags: postgresql
