---
- import_playbook: ansible-version.yml

- hosts: ooni-explorer-next.test.ooni.io
  roles:
    - role: docker_py
    - role: letsencrypt
      letsencrypt_domains: ['explorer-beta.ooni.io']

- hosts: ooni-explorer-next.test.ooni.io
  gather_facts: false # already gathered
  vars:
    ansible_python_interpreter: '/root/venv/bin/python2.7' # to control docker
    explorer_domain: explorer-beta.ooni.io
    explorer_next_tag: '20190319-d612ebf4'
  roles:
    - role: ooni-explorer-next
      tags: explorer
...
