---
- import_playbook: ansible-version.yml

- hosts: mia-ps-test.ooni.nu
  tags: test
  roles:
    - role: docker
      tags: base
    - role: letsencrypt
      tags: base
      letsencrypt_domains:
        - "mia-ps-test.ooni.nu"
        - "ps-test.ooni.io"
        # XXX legacy addresses. Deprecate as soon as traffic drops to zero
        - "events.proteus.test.ooni.io"
        - "registry.proteus.test.ooni.io"
    - role: ooni-bouncer
      tags:
        - service
        - bouncer
    - role: ooni-collector
      with_nginx: no
      tags:
        - service
        - collector
    - role: probe-services
      tags: ps

- hosts: ams-ps.ooni.nu
  roles:
    - role: docker
      tags: base
    - role: letsencrypt
      expand: yes
      tags: base
      letsencrypt_domains:
        - "ams-ps.ooni.nu"
        - "ps.ooni.io"
        - "bouncer.ooni.io"
    - role: ooni-bouncer
      tags:
        - service
        - bouncer
    - role: ooni-collector
      tags:
        - service
        - collector
    - role: probe-services
      tags: ps

- hosts: mia-ps.ooni.nu
  roles:
    - role: docker
      tags: base
    - role: letsencrypt
      tags: base
      letsencrypt_domains:
        - "mia-ps.ooni.nu"
    - role: ooni-bouncer
      tags:
        - service
        - bouncer
    - role: ooni-collector
      tags:
        - service
        - collector
    - role: probe-services
      tags: ps

- hosts: hkg-ps.ooni.nu
  roles:
    - role: docker
      tags: base
    - role: letsencrypt
      tags: base
      letsencrypt_domains:
        - "hkg-ps.ooni.nu"
    - role: ooni-bouncer
      tags:
        - service
        - bouncer
    - role: ooni-collector
      tags:
        - service
        - collector
    - role: probe-services
      tags: ps
