---
- include: ansible-version.yml

- hosts: explorer.ooni.io
  vars:
    letsencrypt_nginx: yes
    letsencrypt_domains: 'explorer.ooni.io,explorer.ooni.torproject.org' # FIXME: comma-delimited string instead of list :-(
  roles:
    ## - letsencrypt # temporary disabled
    - role: ooni-explorer
...
