---
- include: ansible-version.yml

- hosts: orchestration
  become: false
  remote_user: root
  gather_facts: true
  roles:
    - role: adm
      adm_passwd:
        - "{{ passwd.art }}"
        - "{{ passwd.sbs }}"
        - "{{ passwd.darkk }}"

- hosts: orchestration
  gather_facts: false # already gathered
  roles:
    - docker_py

- hosts: db-1.proteus.test.ooni.io
  gather_facts: false
  vars:
    psql_db_name: proteus
    psql_db_user: proteus
    psql_db_passwd: "{{ vault_proteus_database_password_testing }}"
  roles:
    - postgresql
    - proteus-db

- hosts: db-1.proteus.ooni.io
  gather_facts: false
  vars:
    psql_db_name: proteus
    psql_db_user: proteus
    psql_db_passwd: "{{ vault_proteus_database_password }}"
  roles:
    - postgresql
    - proteus-db

- include: deploy-proteus-registry.yml

- include: deploy-proteus-events.yml

- include: deploy-proteus-notify.yml

- include: deploy-proteus-frontend.yml
