---
- import_playbook: ansible-version.yml

- hosts: ams-explorer.ooni.nu
  roles:
    - role: docker
    - role: letsencrypt
      letsencrypt_domains:
        - 'ams-explorer.ooni.nu'
#        - 'explorer.ooni.io'
#        - 'explorer.ooni.org'
#        - 'explorer-beta.ooni.io'
#        - 'ooni-explorer-next.test.ooni.io'
      # expand: true
    - role: explorer
      explorer_domain: 'amsexplorer.ooni.nu'
      tags: explorer
...
