---
- import_playbook: ansible-version.yml

- hosts: monitoring.ooni.org
  roles:
    - role: base-bullseye
    - role: nftables
    - role: monitoring
    - role: dehydrated
      tags: dehydrated
      expand: yes
      ssl_domains:
        - "grafana.ooni.org"
        - "jupyter.ooni.org"
        - "loghost.ooni.org"
        - "monitoring.ooni.org"
        - "netdata.ooni.org"
        - "prometheus.ooni.org"
    - role: prometheus
      tags: prometheus
