---
- import_playbook: ansible-version.yml

- hosts: mia-ps.ooni.io
  roles:
    - role: docker
    - role: letsencrypt
      letsencrypt_domains:
        - "mia-ps.ooni.io"

- hosts: mia-ps.ooni.io
  roles:
    - role: ooni-bouncer
      bouncer_domain: 'mia-ps.ooni.io'
      bouncer_data_dir: '/srv/bouncer'
      bouncer_port: 9000
      with_nginx: no
      tags:
        - service
        - bouncer

    - role: ooni-collector
      collector_domain: 'mia-ps.ooni.io'
      collector_data_dir: '/srv/collector'
      collector_port: 9010
      with_nginx: no
      tags:
        - service
        - collector

    - role: probe-services
      probe_services_domain: "mia-ps.ooni.io"
      bouncer_port: 9000
      collector_port: 9010
      registry_port: 9030
      orchestrate_port: 9031
      tags: ps
