---
- import_playbook: ansible-version.yml

- hosts: "mia-wcth.ooni.io"
  roles:
    - role: docker
    - role: letsencrypt
      letsencrypt_domains:
        - "mia-wcth.ooni.io"
    - role: th-web-connectivity
      tags: wcth
      web_connectivity_domain: mia-wcth.ooni.io
