---
- import_playbook: ansible-version.yml

- hosts: mia-github-webhooks.ooni.nu
  roles:
    - role: docker
    - role: letsencrypt
      expand: yes
      letsencrypt_domains:
        - "mia-github-webhooks.ooni.nu"
        - "github-webhooks.ooni.io"
    - role: github-webhooks
      tags: service
      ssl_domain: "mia-github-webhooks.ooni.nu"
