---

- hosts: vpsbridges
  gather_facts: no
  tags: prereqs
  tasks:
  - name: install ansible prerequisites
    script: setup_ansible_prereqs.sh creates=/root/.ansible_prereqs_installed

- hosts: vpsbridges
  roles:
    - role: nftables
    - role: vpsbridges
      tags: vpsbridges
