---
- include: ansible-version.yml

- hosts: db-1.proteus.test.ooni.io
  gather_facts: false
  vars:
    psql_db_name: proteus
    psql_db_user: proteus
    psql_db_passwd: "{{ proteus_database_password_testing }}"
  roles:
    - postgresql

- hosts: db-1.proteus.ooni.io
  gather_facts: false
  vars:
    psql_db_name: proteus
    psql_db_user: proteus
    psql_db_passwd: "{{ proteus_database_password }}"
  roles:
    - postgresql

- include: deploy-proteus-registry.yml

- include: deploy-proteus-orchestrate.yml

- include: deploy-proteus-notify.yml

- include: deploy-proteus-frontend.yml
