---
# When deploying to a different host you will also have to login to the slack
# admin interface and go into the Apps setting and change the IP whitelist to
# the new IP otherwise it will not work and you will not know why.
- import_playbook: ansible-version.yml

- hosts: ams-slack-1.ooni.org
  roles:
    - role: docker
    - role: letsencrypt-legacy
      tags: letsencrypt
      expand: yes
      letsencrypt_domains:
        - "ams-slack-1.ooni.org"
        - "slack.ooni.org"
        - "slack.ooni.io"
        - "slack.openobservatory.org"
    - role: slackin
      tags: slackin
      ssl_domain: "ams-slack-1.ooni.org"
