---
- hosts: local:staging:testing
  vars:
    ansible_python_interpreter: "/usr/bin/python"
  roles:
    - common
    - docker_py

- hosts: local:staging:testing
  vars:
    ansible_python_interpreter: "/root/venv/bin/python2.7"
    bind_oonibackend_data_path: /data/{{ app_env }}
    bind_oonibackend_tls_dir: "{{ bind_oonibackend_data_path }}/tls"
    enable_tls_bouncer: yes
    enable_collector_alternate: yes
    enable_tls_collector: yes
    enable_tls_web_connectivity: yes
    enable_web_connectivity: yes
    enable_bouncer: yes
    docker_deployment: yes
    enable_tcp_web_connectivity: yes
    enable_tcp_bouncer: yes
    enable_tcp_collector: yes
  roles:
    - letsencrypt
    - ooni-backend
