---
- include: ansible-version.yml

- hosts: [datacollector.infra.ooni.io, hkgmetadb.infra.ooni.io]
  roles:
    - docker_py

- hosts: hkgmetadb.infra.ooni.io
  gather_facts: false # already gathered
  vars:
    ansible_python_interpreter: "/root/venv/bin/python2.7"
  roles:
    - role: plpsql
      tags: plpsql

- hosts: datacollector.infra.ooni.io
  gather_facts: false # already gathered
  vars:
    ansible_python_interpreter: "/root/venv/bin/python2.7"
  roles:
    - airflow
