---
- include: ansible-version.yml

- hosts: msg.ooni.io
  become: false
  remote_user: root
  gather_facts: true
  pre_tasks:
    - name: bootstap python
      raw: if [ ! -x /usr/bin/python ]; then apt-get update && apt-get -y install python-simplejson python-apt; fi
      register: output
      changed_when: output.stdout != ""
  roles:
    - role: adm
      adm_passwd:
        - "{{ passwd.art }}"
        - "{{ passwd.darkk }}"
        - "{{ passwd.sbs }}"

- hosts: msg.ooni.io
  gather_facts: true
  vars:
    letsencrypt_nginx: yes
    letsencrypt_domains: "msg.ooni.io"
  roles:
    - letsencrypt
    - grav
