---
- import_playbook: ansible-version.yml

- hosts: mia-run.ooni.nu
  roles:
    - role: docker
    - role: letsencrypt
      letsencrypt_domains:
        - "mia-run.ooni.nu"
        - "run.ooni.io"
    - role: ooni-run
      tags: service
      ssl_domain: "mia-run.ooni.nu"
