---
- import_playbook: ansible-version.yml

- hosts: ams-pg.ooni.org
  roles:
    - role: ooni-backend
      ssl_domain: ams-pg.ooni.org
    - role: letsencrypt
      tags: letsencrypt
      expand: yes
      letsencrypt_domains:
        - "ams-pg.ooni.org"
        - "api.ooni.io"
        - "collector.ooni.io"
        - "a.collector.ooni.io"
        - "b.collector.ooni.io"
        - "c.collector.ooni.io"
        - "ps.ooni.io"
        - "ps1.ooni.io"
        - "ps2.ooni.io"
        - "ps3.ooni.io"
        - "ps4.ooni.io"

- hosts: ams-pg-test.ooni.org
  roles:
    - role: ooni-backend
      ssl_domain: ams-pg.ooni.org
    - role: letsencrypt
      tags: letsencrypt
      expand: yes
      letsencrypt_domains:
        - "ams-pg-test.ooni.org"
