---
- import_playbook: ansible-version.yml

- hosts: mia-get.ooni.nu
  roles:
    - role: letsencrypt
      letsencrypt_domains:
        - "mia-get.ooni.nu"
        - "get.ooni.io"
        - "get.ooni.torproject.org"
    - role: static-webserver
      domain: 'mia-get.ooni.nu'
