---
- hosts: local:staging:testing
  vars:
    ansible_python_interpreter: "/usr/bin/python"
    bind_oonibackend_data_path: "/data/{{ app_env }}"
    bind_oonibackend_tls_dir: "{{ bind_oonibackend_data_path }}/tls"
  roles:
    - common
    - { role: docker_py, when: docker_deployment is defined }
    - { role: letsencrypt, when: docker_deployment is undefined }

- hosts: local:staging:testing
  vars:
    ansible_python_interpreter: "/root/venv/bin/python2.7"
  roles:
    - { role: letsencrypt, when: docker_deployment is defined }
