---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Ensure $count instances tagged as $group
      ec2:
        key_name: key
        instance_tags: "{{ group }}=true"
        count_tag: "{{ group }}"
        exact_count: "{{ count }}"
        instance_type: t2.micro
        image: ami-e31a6594
        region: eu-west-1
        group_id: sg-bdb072d9 # security group
        wait: yes
#        aws_access_key:
#        aws_secret_key:
      register: ec2_result
  
    - name: Add instances to appropriate $group in inventory
      add_host: hostname={{ item.public_ip }} groupname={{ group }} private_ip={{ item.private_ip }} private_dns={{ item.private_dns_name }}
      with_items: ec2_result.tagged_instances

    - name: Wait for ssh to come up
      local_action: wait_for host="{{ item.public_ip }}"
                    state=started
                    port=22 timeout=120
      sudo: false
      with_items: ec2_result.tagged_instances
