---
# ensure $count number of hosts exist in each $group,
# populate the respective groups in our inventory,
# and wait for the ssh port to respond.
- include: ec.yaml group=munin_masters count=1
- include: ec.yaml group=munin_slaves count=3

- hosts: munin_masters
  remote_user: admin
  roles:
    - munin_master
  sudo: yes

- hosts: munin_slaves
  remote_user: admin
  roles:
    - munin_slave
  sudo: yes

