---
- name: fetch and install deb.torproject.org signing key
  apt_key:
    url: https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc
    id: 'A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89'

- name: installs apt-transport-https
  apt:
    name: apt-transport-https
    state: present
    update_cache: true
    cache_valid_time: '{{ apt_cache_valid_time }}'

- name: adds deb.torproject.org repository and update apt cache
  apt_repository:
    repo: 'deb https://deb.torproject.org/torproject.org {{ ansible_lsb.codename }} main'
    state: present
    update_cache: yes

- name: install tor
  apt:
    name:
      - deb.torproject.org-keyring
      - tor
      - tor-geoipdb
    state: latest
    install_recommends: no

- name: mkdir for data dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ tor_user }}"
    group: "{{ tor_user }}"
    mode: "u=rwx,g=rx,o="
  with_items:
    - "{{ tor_dir }}"
    - "{{ tor_data_dir }}"

- name: torrc
  template: src=torrc dest=/etc/tor/torrc
  notify: restart tor
...
