---
- hosts: ooni-pipeline-hosts
  sudo: yes
  vars:
    - dockers_path: '{{ OONI_SYSADMIN_PATH }}/docker'
  tasks:
  - name: Install ansible requirements for docker
    apt: name={{ item }} update_cache=yes state=latest default_release=testing
    with_items:
      - python-docker
  - name: Checkout oonisysadmin repo
    git: repo=https://github.com/TheTorProject/ooni-sysadmin.git 
         dest={{ OONI_SYSADMIN_PATH }}
  - name: Build (or check) docker images
    docker_image: path={{ item.path }} state=build name={{ item.name }} 
    with_items:
      - { path: '{{ dockers_path }}/backend',
          name: 'bridge-reachability-collector'}
      - { path: '{{ dockers_path }}/probe',
          name: 'bridge-reachability-probe'}
    ignore_errors: True
    register: docker_images
    tags:
       - docker_build
  - name: Run docker containers
    docker: state=running image={{ item.image }} name={{ item.name }}
            volumes={{ item.volumes }}
    with_items:
      - { image: 'ooni/collector',
          name: 'bridge-reachability-collector',
          volumes: "/data/collector/:/data"}
      - { image: 'ooni/probe-bridge-reachability',
          name: 'bridge-reachability-probe',
          volumes: "/data/probe/bridge_reachability/:/data/bridge_reachability/"}
    ignore_errors: True
