---
- name: Get lantern x86_64 deb package
  get_url: >
    url=https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta-64-bit.deb
    dest={{ ansible_env.HOME }}/lantern-installer.deb
  when: ansible_architecture == "x86_64"

- name: Get lantern i386 deb package
  get_url: >
    url=https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta-32-bit.deb
    dest={{ ansible_env.HOME }}/lantern-installer.deb
  when: ansible_architecture == "i386"

- name: Install lantern package dependencies
  apt: name=libappindicator3-1

- name: Install lantern deb package
  apt: deb="{{ ansible_env.HOME }}/lantern-installer.deb"
