---
- name: Create dir
  tags: slack-irc
  file:
    path: "/srv/slack-irc"
    state: directory

- name: Create slack-irc-bridge config
  tags: slack-irc
  copy:
    content: "{{ slack_irc_config | to_nice_json }}"
    dest: "/srv/slack-irc/config.json"
  notify: restart slack-irc-bridge

- name: Deploy slackin container
  docker_container:
    name: slackin
    image: emedvedev/slackin-extended
    restart_policy: unless-stopped
    published_ports: "3000:3000"
    env:
      SLACKIN_VERSION: latest
      SLACK_SUBDOMAIN: "{{ slackin_org }}"
      SLACK_API_TOKEN: "{{ slackin_token }}"

- name: Deploy slack-irc-bridge container
  tags: slack-irc
  docker_container:
    name: slack-irc-bridge
    image: openobservatory/sysadmin-slack-irc:20211221-22e6b41d
    restart_policy: unless-stopped
    volumes:
      - "/srv/slack-irc:/slack-irc"

- name: Add nginx virtual host config
  template:
    src: slackin-nginx
    dest: /etc/nginx/sites-enabled/slackin
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
