- name: untar proteus tarball
  unarchive:
    src: "{{ proteus_tarball_url }}"
    dest: "{{ proteus_install_path }}"
    mode: 0755
    owner: "{{ proteus_user }}"
    group: "{{ proteus_group }}"
    copy: no

- name: Configure Proteus
  notify:
  - reload proteus
  template:
    src: proteus-notify.toml.j2
    dest: "{{ proteus_config_path }}/proteus-notify.toml"

- name: Write Proteus APN key
  notify:
  - reload proteus
  copy:
    content: "{{ proteus_apn_key_content }}"
    dest: "{{ proteus_config_path }}/apn-key.pem"

- name: Install proteus systemd service file
  notify:
  - restart proteus
  template:
    src: proteus-notify.service
    dest: /etc/systemd/system/proteus-notify.service

- name: Enable and start proteus service
  systemd:
    name: proteus-notify.service
    state: started
    enabled: yes
    daemon_reload: yes
