- apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - munin
    - nginx
    - libnet-ssleay-perl

- name: Configure munin master
  template: src=munin.conf
            dest=/etc/munin/munin.conf
            owner=root group=root mode=0644

- name: Install munin SSL cert
  template: src=private/ssl-cert-munin.pem
            dest=/etc/munin/ssl-cert-munin.pem
            owner=munin group=munin mode=0644

- name: Install munin SSL key
  template: src=private/ssl-key-munin.pem
            dest=/etc/munin/ssl-key-munin.pem
            owner=munin group=munin mode=0600

- name: Install munin-error-counting plugin
  template: src=munin_errors
            dest=/etc/munin/plugins/munin_errors
            owner=root group=root mode=0755

- name: Restart munin-node
  service: name=munin-node state=restarted

- name: Install nginx SSL cert
  template: src=private/ssl-cert-nginx.pem
            dest=/etc/ssl/certs/ssl-cert-nginx.pem
            owner=root group=root mode=0644

- name: Install nginx SSL key
  template: src=private/ssl-key-nginx.pem
            dest=/etc/ssl/private/ssl-key-nginx.pem
            owner=root group=root mode=0600

- name: Configure nginx
  template: src=nginx.conf
            dest=/etc/nginx/nginx.conf
            owner=root group=root mode=0644

- name: Install basic auth password file
  template: src=private/basic-auth
            dest=/etc/nginx/basic-auth
            owner=root group=root mode=0644

- name: Restart nginx
  service: name=nginx state=restarted
